name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build and test for ${{ matrix.os }} - ${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        env:
            CI: true
            PLAYWRIGHT_BROWSERS_PATH: 0

        strategy:
            fail-fast: false
            matrix:
                node-version: [12.x, 16.x]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install --legacy-peer-deps

            - name: Run Tests
              run: npm test
